mayuresh82/alert_manager

listener/parsers/parser_kapacitor.go
listener/parsers/parser_test.go

Fix kapacitor parser

---

api/README.md
handler/config.go
handler/handler.go
handler/handler_test.go
handler/suppress.go
handler/suppress_test.go
internal/models/query.go
internal/models/suppress.go
plugins/processors/aggregator/aggregator.go
plugins/processors/aggregator/aggregator_test.go
template/schema.go

- add match cond to rule itself
- allow regex suppression
- fix api query

Modify suppression logic and allow regex matches

---

handler/handler.go
handler/handler_test.go
internal/stats/stats.go

Add clear holddown mechanism so alerts are not cleared right away and use a holddown timer to avoid flaps

Add clear holddown mechanism and internal stats

---

.gitignore
api/server.go
handler/handler.go
internal/models/alert.go

supp rule bugfix

---

alert_config.yaml
handler/config.go
handler/handler.go
handler/handler_test.go
internal/models/alert.go
plugins/processors/aggregator/aggregator.go
plugins/processors/aggregator/aggregator_test.go
plugins/processors/aggregator/grouper.go
plugins/processors/aggregator/groupers/bgp.go
plugins/processors/aggregator/groupers/grouper_test.go
plugins/processors/aggregator/groupers/label_grouper.go
testutil/testdata/test_config.yaml

Adds a generic label based grouper

Add label based generic grouper

---

api/server_test.go
handler/handler.go
handler/handler_test.go
handler/registry.go
internal/models/alert.go
plugins/processors/aggregator/aggregator.go
plugins/processors/aggregator/aggregator_test.go
plugins/processors/all/all.go
plugins/processors/notifier/notifier.go
plugins/processors/notifier/notifier_test.go
plugins/transforms/netbox/netbox.go

Round 3 = add notifier into the pipeline so now we have inhibitor -> aggregator -> notifier

Add notifier into the pipeline

---

README.md
alert_manager.go
api/server.go
config.go
handler/handler.go
handler/handler_test.go
handler/suppress.go
internal/models/alert.go
internal/models/models.go
internal/models/query.go
internal/models/query_test.go
internal/models/suppress.go
plugins/outputs/influx.go
plugins/processors/aggregator/aggregator.go
plugins/processors/aggregator/groupers/bgp.go
plugins/processors/aggregator/groupers/dc_link.go
plugins/processors/aggregator/groupers/fibercut.go
plugins/processors/inhibitor/inhibitor.go
plugins/processors/notifier/notifier.go
template/schema.go

adds teamview support . Uses db partitioning to separate alerts for various teams.

Teamview support

---

handler/handler.go
internal/models/models.go
plugins/outputs/email.go
plugins/outputs/outputs_test.go
plugins/outputs/slack.go
plugins/outputs/victorops.go
plugins/processors/aggregator/aggregator.go
sample_config.toml

this allows per-team settings for slack channel, email recipient , victorops url etc.

Add support for per team notification channels

---

api/server.go

fix bug that was not creating supp rules

fix supprule bug

---

ui/.dockerignore
ui/Dockerfile
ui/package-lock.json
ui/public/index.html
ui/src/components/Alert.js
ui/src/library/AlertManagerApi.js

Exclude alerts already part of an aggregate from main view
Add option to suppress alert for 7d

Minor fixes for UI 

---

internal/models/alert.go

attempting to fix some pg deadlocks

deadlock fix- remove for update from some queries

---

api/server.go
api/server_test.go
handler/suppress.go
testutil/testdata/test_config.yaml

Add api endpoint to get persistent rules

---

alert_config.yaml
alert_manager.go
api/server.go
config.go
handler/config.go
handler/handler.go
handler/handler_test.go
internal/models/alert.go
internal/models/query.go
internal/models/query_test.go
internal/models/teams.go
listener/parsers/parser_prom.go
listener/parsers/parser_test.go
plugins/outputs/email.go
plugins/outputs/influx.go
plugins/outputs/outputs_test.go
plugins/outputs/slack.go
plugins/outputs/victorops.go
plugins/plugins.go
plugins/processors/aggregator/aggregator.go
plugins/processors/aggregator/aggregator_test.go
plugins/transforms/netbox/netbox.go
sample_config.toml
template/schema.go

- add prometheus parser
- add basic user management and support for static user config + api
- remove default timerange from queries
- move agg alert check from aggregator to handler
- move netbox panic handling to handler
- misc

Several changes

---

alert_manager.go
api/server.go
api/server_test.go
config.go
sample_config.toml

adds an admin user support that generates a token with no expiry

Add admin account

---

plugins/outputs/amqp.go

default amqp connect timeout

---

ui/package-lock.json
ui/package.json
ui/src/components/Alerts/AlertItem.js
ui/src/components/Alerts/HistoryItem.js
ui/src/components/AlertsTable2.js
ui/src/components/PageHelp.js
ui/src/components/Select/SelectDevicesList.js
ui/src/components/Select/SelectSitesList.js
ui/src/components/SuppressionRule/SuppressionRuleItem.js
ui/src/views/AlertView.jsx
ui/src/views/AlertsExplorerView.jsx
ui/src/views/OngoingAlertsView.jsx

fix rendering of elements from api, make a couple additions to supprule page

Fix rendering and misc

---

handler/handler.go
handler/handler_test.go

Also suppress agg alert

---

ui/src/components/Alerts/AlertItem.js
ui/src/components/SuppressionRule/SuppressionRuleItem.js
ui/src/components/SuppressionRule/SuppressionRuleMenu.js
ui/src/library/AlertManagerApi.js
ui/src/views/AlertView.jsx
ui/src/views/OngoingAlertsView.jsx
ui/src/views/SuppRulesList.jsx

- add ability to clear a supprule from UI
-  add ability to create a new supprule from UI

Ui supp menu

---

ui/src/views/SuppRulesList.jsx

mark required fields

---

handler/handler.go
plugins/outputs/amqp.go

Allow to disable holddown and fix amqp retry

Allow to disable holddown and fix amqp retry

---

internal/models/query.go
ui/src/library/AlertManagerApi.js
ui/src/views/AlertsExplorerView.jsx
ui/src/views/OngoingAlertsView.jsx

fix alerts display when there are a large number of suppressed alerts returned

Fix UI ongoing alerts display

---

handler/handler.go
plugins/processors/notifier/notifier.go

suppressed alerts were getting notified. This fixes that.

Fix supp notifier bug

---

plugins/processors/aggregator/groupers/fibercut.go
sample_config.toml

Aggregating fibercut alert messages where a-side matches z-side

---

ui/src/components/AlertsTable/TableBody.js
ui/src/components/ToolTip.js
ui/src/library/AlertManagerApi.js
ui/src/library/utils.js
ui/src/views/AlertsView.js

1. Change the "last_active" from timestamp to "time since last update"
2. Add hover tooltip that displays the last update
3. Change color of hover for "more info" to make it more obvious that it is a link 
4. Fixed format of "time since" last active
5. Fixed the colors for the "severity" cells.

[ui] Change 'last active' to time since; add last update on hover

---

listener/parsers/parser_ns1.go

Fix ns1 parser

---

ui/package-lock.json
ui/package.json
ui/src/App.js
ui/src/components/AlertsTable/AlertsTable.js
ui/src/components/AlertsTable/PaginationToolbar.js
ui/src/components/AlertsTable/SelectToolbar.js
ui/src/components/AlertsTable/TableBody.js
ui/src/components/AlertsTable/TableHeader.js
ui/src/components/AlertsTable/columns.js
ui/src/components/Filters/FilterCheckbox.js
ui/src/components/Filters/FilterInput.js
ui/src/components/Filters/FilterMultiSelect.js
ui/src/components/Filters/FilterSelect.js
ui/src/components/Filters/FilterToolbar.js
ui/src/components/Header/Header.js
ui/src/components/NotificationBar.js
ui/src/components/ToolTip.js
ui/src/components/checkbox.js
ui/src/components/contexts/FilterContext.js
ui/src/components/contexts/NotificationContext.js
ui/src/components/contexts/TableContext.js
ui/src/library/utils.js
ui/src/views/AlertsView.js

I made this work constrained to pages. So you will not "select all" and end up selecting items off the page which would make for easy mistakes.
1. Add bulk select feature to "clear" and "acknowledge" alerts
2. Move all shared state into contexts
3. Remove "details" column and have the row click open up the alert details page
4. Create notifications and alerts (used to inform user of the action they have taken with bulk select)
5. [Moved some state/actions into a reducer to make it more legible and easier to code instead of passing tons of props around.
6. Bug fixes from the console, e.g adding "key" to components for React to use when rendering
7. Made sure filters/selections cleared on new fetches of alerts as well as page changes.

[ui] Adding Bulk Select Feature

---

handler/handler.go
handler/handler_test.go

we were missing notifications when a de-deuped alert is reactivated

notify on alert reactivation

---

alert_manager.go
internal/stats/stats.go
internal/stats/stats_test.go
listener/webhook_test.go

Make stats package configurable so it can be imported by other apps

Make stats package configurable

---

handler/handler.go
handler/handler_test.go

Update start time for deduped alerts to current

Update start time for deduped alerts to current

---

ui/src/components/AlertsTable/TableBody.js
ui/src/components/AlertsTable/TableHeader.js
ui/src/index.css

1. Bugfix for hover on rows
2. Clean up table borders to make it less distracting.

[bugfix] Fix table row highlight borders; remove cell borders

---

api/server.go
api/server_test.go
handler/handler.go
handler/handler_test.go

- add an escalate alert action
- add ability to disable notifications for alert actions

Add alert escalate action and option to not notify

---

plugins/processors/aggregator/aggregator.go
plugins/processors/aggregator/grouper.go

fix the grouper selection mechanism in case two different alerts arrive at the same time for the same grouper

Grouper fix

---

.dockerignore
.gitignore
db/dev.Dockerfile
dev.Dockerfile
docker-compose.yml
ui/dev.Dockerfile
ui/package-lock.json

This will allow us to spin up a dev environment locally on our laptops with a single command `docker-compose up`. It includes:
1. DB with data from a local sql dump file
2. API with hot reloading.
3. WEB with hot reloading
**NOTE:**
1. The API and WEB have the local repo (on your laptop) bind mounted into the containers so you can develop like normal and the containers will reload the services so it picks up the changes. 
2. We still need to solve the problem of how to easily automate getting the sql dump file and creating the config.toml file on the users local laptop.

Create a dev environment with one-command

---

handler/handler.go
internal/models/alert.go

fix dedup logic so that disable_dedup now only works against reactivating old alerts and doesnt affect existing active alerts

fix dedup logic

---

alert_manager.go
api/server.go
config.go

make api server timeout configurable

make api server timeout configurable

---

listener/parsers/parser_generic.go
listener/parsers/parser_grafana.go
listener/parsers/parser_kapacitor.go
listener/parsers/parser_ns1.go
listener/parsers/parser_observium.go
listener/parsers/parser_prom.go
listener/parsers/parser_test.go
listener/webhook.go
listener/webhook_test.go

this is primarily to satisfy the prometheus use case that sends multiple alerts per http post

Allow parsing multiple alerts per request
